name: Download and Push XCFramework from AWS CodeArtifact

on:
  push:
    branches:
      - cd  # Trigger on push to the main branch (adjust as needed)
  workflow_dispatch:  # Manual trigger

permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read  

jobs:
  download-xcframework:
    runs-on: ubuntu-latest

    steps:
      # Step 2: Set up AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::003367508252:role/github-devops-tools"
          aws-region: "us-east-1"
          audience: "sts.amazonaws.com"

      # Step 3: Download the zipped XCFramework from AWS CodeArtifact
      - name: Download XCFramework from CodeArtifact
        run: |
          aws codeartifact get-package-version-asset \
            --domain caf \
            --domain-owner 003367508252 \
            --repository development \
            --package ios-iproovprovider \
            --package-version 1.0.0 \
            --asset ios-iproovprovider \
            --format generic
            Faceliveness

      # Step 4: Unzip the downloaded package
      - name: Unzip the XCFramework
        run: |
          unzip ios-iproovprovider.zip -d ./  # Specify where to unzip

      # Step 5: Add, commit, and push the extracted XCFramework to the repository
      # - name: Commit and Push Changes
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"

      #     # Add the extracted files to the git staging area
      #     git add ./path/to/extract/*  # Add the extracted files

      #     # Commit the changes
      #     git commit -m "Add XCFramework package"

      #     # Push changes to the repository
      #     git push origin main  # Push to the main branch (adjust as needed)
